# Generated by Django 5.1.2 on 2024-10-18 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletin',
            old_name='fecha_publicacion',
            new_name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='boletin',
            name='requerimiento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.requerimientos'),
            preserve_default=False,
        ),
    ]
