# Generated by Django 5.1.2 on 2024-10-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fecha_publicacion_boletin_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requerimientos',
            new_name='Requerimiento',
        ),
    ]
