# Generated by Django 5.1.2 on 2024-10-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_requerimientos_requerimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='estados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
