# Generated by Django 5.1.2 on 2024-11-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_requerimiento_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
    ]
