# Generated by Django 5.1.2 on 2024-11-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_boletin_es_publico'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletin',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boletin',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
    ]
