# Generated by Django 5.2.1 on 2025-05-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_boletin_descargas_boletin_vistas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=500)),
                ('estado', models.IntegerField(default=1)),
            ],
        ),
    ]
