# Generated by Django 5.2.1 on 2025-06-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_fuente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquetas', models.TextField(default='[]')),
                ('resumen', models.CharField(max_length=2500)),
                ('estado', models.IntegerField(default=-1)),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.fuente')),
            ],
        ),
    ]
